<a href="https://colab.research.google.com/github/Hokyungjin-Team/colab/blob/main/%EC%84%A0%ED%98%95%EB%8C%80%EC%88%98%ED%95%992_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**프린트**

In [ ]:
print ("Hello, world")

# integer
x=3
print("정수: %01d,%02d,%03d,%04d,%05d"
      %(x,x,x,x,x))

# float
x=256.123
print("실수: %.0f,%.1f,%.2f"
       %(x,x,x))
#string
x="Hello, world"
print("문자열: [%s]" % (x))



Hello, world
정수: 3,03,003,0003,00003
실수: 256,256.1,256.12
문자열: [Hello, world]


반복문,조건문

In [ ]:
contents=["Regression","Classification", "SYM","Clustering","Dimension reduction",
          "NN","CNN","AE","GAN","RNN"]

for con in contents:
  if con in ["Regression","Classification", "SYM","Clustering","Dimension reduction"]:
    print ("%s 은(는) 기계학습 내용입니다." %con)
  elif con in ["CNN"]:
    print("%s 은(는) convolutional neural network 입니다." %con)
  else:
    print("%s 은(는) 심층학습 내용입니다." %con)


Regression 은(는) 기계학습 내용입니다.
Classification 은(는) 기계학습 내용입니다.
SYM 은(는) 기계학습 내용입니다.
Clustering 은(는) 기계학습 내용입니다.
Dimension reduction 은(는) 기계학습 내용입니다.
NN 은(는) 심층학습 내용입니다.
CNN 은(는) convolutional neural network 입니다.
AE 은(는) 심층학습 내용입니다.
GAN 은(는) 심층학습 내용입니다.
RNN 은(는) 심층학습 내용입니다.


**반복문과 인덱스**

In [ ]:
for(i,con) in enumerate(contents):
  print("[%d/%d]: %s" %(i,len(contents),con))

[0/10]: Regression
[1/10]: Classification
[2/10]: SYM
[3/10]: Clustering
[4/10]: Dimension reduction
[5/10]: NN
[6/10]: CNN
[7/10]: AE
[8/10]: GAN
[9/10]: RNN


**함수**

In [ ]:
def sum(a,b):
  return a+b

x=10.0
y=20.0
print("%.1f +%.1f = %.1f"%(x,y,sum(x,y)))

10.0 +20.0 = 30.0


**리스트**

In [ ]:
a=[]
b=[1,2,3]
c=["Hello",",","world"]
d=[1,2,3,"x","y","z"]
x=[]
print(x)

x.append('a')
print(x)

x.append(123)
print(x)

x.append(["a","b"])
print(x)

[]
['a']
['a', 123]
['a', 123, ['a', 'b']]


**딕셔러니(dictionary)**

In [ ]:
dic=dict()
dic["name"]="Daesik"
dic["town"]="Yongin city"
dic["job"]="Assistant professor"
print(dic)

{'name': 'Daesik', 'town': 'Yongin city', 'job': 'Assistant professor'}


**클래스**

In [ ]:
class Student:
    #생성자
    def __init__(self,name):
      self.name =name
    #메써드
    def study(self,hard=False):
      if hard:
        print ("%s 학생은 열심히 공부합니다."%self.name)
      else:
        print ("%s 학생은 공부합니다."%self.name)

s=Student("Dasesik")
s.study()
s.study(hard=True)


Dasesik 학생은 공부합니다.
Dasesik 학생은 열심히 공부합니다.


**라이브러리(패키지)로드**

In [ ]:
import numpy as np

**2.벡터,행렬 연산,그래프 그리기**

**프린트**

In [ ]:
def print_val(x):
    print ("Type:",type(x))
    print ("Shape:",x.shape)
    print ("값:\n",x)
    print (" ")

**rank 1 np array**

In [ ]:
x = np.array([1, 2, 3])
print_val(x)

x[0]= 5
print_val(x)

Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [1 2 3]
 
Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [5 2 3]
 


**rank 2 np array**

In [ ]:
y= np.array([[1,2,3],[4,5,6]])
print_val(y)

Type: <class 'numpy.ndarray'>
Shape: (2, 3)
값:
 [[1 2 3]
 [4 5 6]]
 


**rank 2 zeros**

In [ ]:
a=np.zeros((2,2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[0. 0.]
 [0. 0.]]
 


**rank 2 ones**

In [ ]:
a =np.ones((3,2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 2)
값:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 


**rank 2 단위 행렬(identity matrix)**

In [ ]:
a=np.eye(3,3)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 3)
값:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
